package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class AdjTypeJa implements java.io.Serializable {
  public abstract <R,A> R accept(AdjTypeJa.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAdjTypeNa p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAdjTypeI p, A arg);

  }

}
