package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EAdjectiveJa extends Pattern {
  public final AdjectivePattern adjectivepattern_;
  public final AdjTypeJa adjtypeja_;

  public EAdjectiveJa(AdjectivePattern p1, AdjTypeJa p2) { adjectivepattern_ = p1; adjtypeja_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EAdjectiveJa) {
      net.lemonmodel.patterns.parser.Absyn.EAdjectiveJa x = (net.lemonmodel.patterns.parser.Absyn.EAdjectiveJa)o;
      return this.adjectivepattern_.equals(x.adjectivepattern_) && this.adjtypeja_.equals(x.adjtypeja_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.adjectivepattern_.hashCode())+this.adjtypeja_.hashCode();
  }


}
